import type { Capability } from "./registry.js";

export const CAPABILITY_LABELS: Record<Capability, string> = {
  "activities.read.all": "Leggi tutte le attività",
  "activities.create": "Crea attività",
  "activities.update.own": "Modifica le proprie attività",
  "activities.update.any": "Modifica qualsiasi attività",
  "activities.delete.own": "Cancella le proprie attività",
  "activities.delete.any": "Cancella qualsiasi attività",
  "activities.export": "Esporta CSV",
  "aziende.read": "Leggi anagrafica aziende",
  "aziende.create": "Crea aziende",
  "aziende.update": "Modifica aziende",
  "aziende.delete": "Cancella aziende",
  "activity_types.read": "Leggi tipi attività",
  "activity_types.manage": "Gestisci tipi attività",
  "trash.read.own": "Vedi cestino proprio",
  "trash.read.any": "Vedi cestino di chiunque",
  "trash.restore.own": "Ripristina propri record",
  "trash.restore.any": "Ripristina record altrui",
  "trash.purge": "Cancella subito (no 7gg)",
  "roles.read": "Leggi ruoli",
  "roles.manage": "Gestisci ruoli",
  "roles.assign": "Assegna ruoli agli utenti",
  "allowlist.read": "Leggi allowlist",
  "allowlist.manage": "Gestisci allowlist",
  "audit.read": "Leggi audit log",
  "users.read.all": "Leggi profili di tutti gli utenti",
  "users.approve": "Approva utenti in attesa",
  "payments.read": "Vedi pagamenti propri",
  "payments.read.any": "Vedi pagamenti di chiunque",
  "payments.manage": "Segna pagamenti propri",
  "payments.manage.any": "Cancella pagamenti di chiunque",
  "conti.proforma": "Genera pro forma",
  "conti.emit": "Emetti conti formali",
  "conti.saldo": "Segna conti saldati",
  "reminders.read": "Leggi promemoria",
  "reminders.create": "Crea promemoria",
  "reminders.update.own": "Modifica i propri promemoria",
  "reminders.update.any": "Modifica qualsiasi promemoria",
  "reminders.delete.own": "Cancella i propri promemoria",
  "reminders.delete.any": "Cancella qualsiasi promemoria",
};
